<?php

namespace Database\Seeders;

use App\Models\UserPermission;
use Illuminate\Database\Seeder;

class UserPermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $permissions = [
            [
                'role_name' => 'Super Admin',
                'status' => true,
                'dashboard_view' => true,
                // All permissions set to true for Super Admin
                'login_menu_view' => true,
                'login_menu_delete' => true,
                'login_menu_update' => true,
                'login_menu_create' => true,
                'job_menu_view' => true,
                'job_menu_delete' => true,
                'job_menu_update' => true,
                'job_menu_create' => true,
                'manual_job_menu_view' => true,
                'manual_job_menu_delete' => true,
                'manual_job_menu_update' => true,
                'manual_job_menu_create' => true,
                'quality_menu_view' => true,
                'quality_menu_delete' => true,
                'quality_menu_update' => true,
                'quality_menu_create' => true,
                'user_menu_view' => true,
                'user_menu_delete' => true,
                'user_menu_update' => true,
                'user_menu_create' => true,
                'role_menu_view' => true,
                'role_menu_delete' => true,
                'role_menu_update' => true,
                'role_menu_create' => true,
                'status_menu_view' => true,
                'status_menu_delete' => true,
                'status_menu_update' => true,
                'status_menu_create' => true,
                'sub_status_menu_view' => true,
                'sub_status_menu_delete' => true,
                'sub_status_menu_update' => true,
                'sub_status_menu_create' => true,
                'sheet_size_view' => true,
                'sheet_size_delete' => true,
                'sheet_size_update' => true,
                'sheet_size_create' => true,
                'material_master_view' => true,
                'material_master_delete' => true,
                'material_master_update' => true,
                'material_master_create' => true,
                'machine_master_view' => true,
                'machine_master_delete' => true,
                'machine_master_update' => true,
                'machine_master_create' => true,
                'standerd_production_view' => true,
                'standerd_production_delete' => true,
                'standerd_production_update' => true,
                'standerd_production_create' => true,
                'alert_view' => true,
                'alert_delete' => true,
                'alert_update' => true,
                'alert_create' => true,
                'tag_view' => true,
                'tag_delete' => true,
                'tag_update' => true,
                'tag_create' => true,
                'job_creation_view' => true,
                'job_creation_delete' => true,
                'job_creation_update' => true,
                'job_creation_create' => true,
                'shift_view' => true,
                'shift_delete' => true,
                'shift_update' => true,
                'shift_create' => true,
                'machine_type_create' => true,
                'machine_type_delete' => true,
                'machine_type_update' => true,
                'machine_type_view' => true,
                'department_view' => true,
                'department_delete' => true,
                'department_update' => true,
                'department_create' => true,
                'process_view' => true,
                'process_delete' => true,
                'process_update' => true,
                'process_create' => true,
                'QCMAster_view' => true,
                'QCMAster_delete' => true,
                'QCMAster_update' => true,
                'QCMAster_create' => true,
                'Button_group_view' => true,
                'Button_group_delete' => true,
                'Button_group_update' => true,
                'Button_group_create' => true,
                'buttons_view' => true,
                'buttons_delete' => true,
                'buttons_update' => true,
                'buttons_create' => true,
                'DMTask_view' => true,
                'DMTask_delete' => true,
                'DMTask_update' => true,
                'DMTask_create' => true,
                'dailyTask_view' => true,
                'dailyTask_delete' => true,
                'dailyTask_update' => true,
                'dailyTask_create' => true,
                'DMI_view' => true,
                'DMI_delete' => true,
                'DMI_update' => true,
                'DMI_create' => true,
            ],
            [
                'role_name' => 'Supervisor',
                'status' => true,
                'dashboard_view' => true,
                'login_menu_view' => true,
                'job_menu_view' => true,
                'job_menu_update' => true,
                'job_menu_create' => true,
                'manual_job_menu_view' => true,
                'manual_job_menu_create' => true,
                'quality_menu_view' => true,
                'quality_menu_create' => true,
                'user_menu_view' => true,
                'status_menu_view' => true,
                'sub_status_menu_view' => true,
                'material_master_view' => true,
                'machine_master_view' => true,
                'shift_view' => true,
                'process_view' => true,
                'QCMAster_view' => true,
                'DMI_view' => true,
                'DMI_create' => true,
            ],
            [
                'role_name' => 'Operator',
                'status' => true,
                'dashboard_view' => true,
                'login_menu_view' => true,
                'job_menu_view' => true,
                'manual_job_menu_view' => true,
                'quality_menu_view' => true,
                'DMI_view' => true,
                'DMI_create' => true,
            ],
            [
                'role_name' => 'QC Inspector',
                'status' => true,
                'dashboard_view' => true,
                'quality_menu_view' => true,
                'quality_menu_create' => true,
                'quality_menu_update' => true,
                'QCMAster_view' => true,
                'job_menu_view' => true,
            ],
            [
                'role_name' => 'Viewer',
                'status' => true,
                'dashboard_view' => true,
                'login_menu_view' => true,
                'job_menu_view' => true,
                'manual_job_menu_view' => true,
                'quality_menu_view' => true,
                'user_menu_view' => true,
                'material_master_view' => true,
                'machine_master_view' => true,
            ],
        ];

        foreach ($permissions as $permission) {
            UserPermission::create($permission);
        }

        $this->command->info('User permissions seeded successfully!');
    }
}
